### ISSUE TITLE
Player crashes with external .ass subtitle file.

### ISSUE THREAD

**Issue by ufufufu** [Blitzker/assfiltermod#1]
Media players (MPC-HC, PotPlayer) will crash if I load a video that has an accompanying external *.ass subtitle file. It doesn't matter if the video file has internal subtitles or not.
This didn't happen with external *.srt subtitles files.

**Comment by amayra** [comment]
can you upload ass file ?

**Comment by ufufufu** [comment]
[example file](https://miku.hatsune.my/mizuha/secretlifeofpet.ass)

**Comment by amayra** [comment]
http://s000.tinyupload.com/index.php?file_id=04265098328376905021

**Comment by amayra** [comment]
http://s000.tinyupload.com/index.php?file_id=04265098328376905021                                                                      
i fix this file for you

**Comment by ufufufu** [comment]
And MPC-HC/PotPlayer still crashed.
BTW, this crashing problem only starts with harfbuzz_x4. harfbuzz_x3 works fine.

**Comment by amayra** [comment]
strange, seems to work fine on my MPC-HC 1.7.20.270 assfilter mod and harfbuzz_x4 64bit 
usually this kind of problem come when you have ass file with bad "Script Info" try to open orignal file with aegisub and editing  [http://docs.aegisub.org/manual/Properties](script properties)

**Comment by Blitzker** [comment]
This was a bug with a test version that wasn't on github yet. Please test with the latest release.

**Comment by Blitzker** [comment]
Fixed in the last release.

**Comment by RadarNyan** [comment]
I'm still experiencing problem (player crash / hang) while trying to play video with external subs, can you confirm this problem has been fixed?

Internal subs (embedded in mkv files) works just fine, if I attach the external ass file into the video file with MKVToolNix, then the subtitle can be loaded and renders just fine.

MPC-HC 64-bit 1.7.13
assfiltermod_v0.3_x64
(EDIT: also tried 32-bit version of MPC-HC & assfiltermod, same problem)

**Comment by RadarNyan** [comment]
I've tried the latest release (v0.4) and even tried to make my own build from the latest code, still it doesn't work for me.

When playing a video, .mkv file with ass sub embedded with MPC-HC + assfiltermod, everything woks fine. The subtitle renders fine, the assfiltermod tray icon shows up and open it the Status tab confirms it's working.

However if I try to play the same video, except this .mkv file **doesn't** have any sub embedded, and a .ass sub file (the one embedded in the previous .mkv file) locates in the same directory with same filename, the player (MPC-HC) would crash at start and gives me an error report:

https://drdump.com/UploadedReport.aspx?DumpID=18646527&SecondVisit=1

I also tried an external .srt sub file, this time MPC-HC didn't crash, I have assfiltermod tray icon shows up, and open it the Status tab "Track Name" shows the correct path to .srt file but there's no subtitle rendered on screen at all.

I'm using Windows 7 SP1 x64 English version, with system code page set to 932 (Japanese) I've tried to change it to 437 (United States) but that didn't fix the problem for me.

@Blitzker Can you please look into this problem?

**Comment by RadarNyan** [comment]
As HPC-HC has been discontinued, I tried to use PotPlayer (32-bit) / MadVR / assfiltermod v0.4.
Same problem, this time madVR crashes with the following report:
```
date/time          : 2017-12-22, 07:23:43, 202ms
computer name      : MM-AURORAR3
user name          : Misaki
registered owner   : Microsoft / Microsoft
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Japanese
system up time     : 19 hours 55 minutes
program up time    : 1 minute 57 seconds
processors         : 8x Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
physical memory    : 5572/8174 MB (free/total)
free disk space    : (C:) 1.47 GB
display mode       : 1920x1080, 32 bit
process id         : $494
allocated memory   : 656.14 MB
largest free block : 1.99 GB
executable         : PotPlayerMini.exe
current module     : MADHCNET32.DLL
module date/time   : 2017-09-13 17:25
version            : 1.0.18.0
compiled with      : Delphi XE8
madExcept version  : 4.0.18
madVR version      : 0.92.10
callstack crc      : $6c6c8b28, $d4da6789, $5897994d
exception number   : 1
exception class    : Exception
exception message  : Access violation at address $6c6c8b28 in module 'assfiltermod.dll'. Read of address $54.

CFrameQueue::SubtitleThread ($e20):
6c6c8b28 +000 assfiltermod.dll
4a442429 +3f9 madVR.ax         framequeue.cpp 12280 +113 CFrameQueue.RequestSubtitles
4a44255e +09e madVR.ax         framequeue.cpp 12318   +9 CFrameQueue.SubtitleThread
4a4430c4 +004 madVR.ax         framequeue.cpp   201   +0 Queue_SubtitleThread
76683368 +010 kernel32.dll                               BaseThreadInitThunk

main thread ($dc0): <priority:2>
77b30166 +0e ntdll.dll                         NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll                    WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll                      WaitForMultipleObjectsEx
7578087c +00 USER32.dll                        MsgWaitForMultipleObjectsEx
75780b7c +1a USER32.dll                        MsgWaitForMultipleObjects
4a45ebb3 +f3 madVR.ax       madvr.cpp 1368 +19 CVideoRenderer.RunCallback
75780d60 +16 USER32.dll                        CallWindowProcW
76683368 +10 kernel32.dll                      BaseThreadInitThunk

thread $1c0:
77b30166 +0e ntdll.dll     NtWaitForMultipleObjects
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $650:
77b31f4f +0b ntdll.dll     NtWaitForWorkViaWorkerFactory
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $10c0:
75777908 +26 USER32.dll    GetMessageW
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $19a0:
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1a98:
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $17f0:
77b31f4f +0b ntdll.dll     NtWaitForWorkViaWorkerFactory
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $15a4:
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $10dc:
77b31f4f +0b ntdll.dll     NtWaitForWorkViaWorkerFactory
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $106c:
75777908 +26 USER32.dll    GetMessageW
76683368 +10 kernel32.dll  BaseThreadInitThunk

WindowQueueThread ($1af0): <priority:2>
75777908 +026 USER32.dll                          GetMessageW
098b02b6 +106 MADHCNET32.DLL madNetTools 1427 +17 WindowQueueThread
76683368 +010 kernel32.dll                        BaseThreadInitThunk

thread $19d0:
77b2fcb3 +0b ntdll.dll                  NtReplyWaitReceivePortEx
098ab6f3 +4b MADHCNET32.DLL madCodeHook LpcPortThread
76683368 +10 kernel32.dll               BaseThreadInitThunk

thread $14d0: <priority:1>
77b2f8da +0e ntdll.dll                  NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll             WaitForSingleObjectEx
7668118f +3e kernel32.dll               WaitForSingleObjectEx
76681143 +0d kernel32.dll               WaitForSingleObject
098ab3c2 +12 MADHCNET32.DLL madCodeHook LpcDispatchThread
76683368 +10 kernel32.dll               BaseThreadInitThunk

thread $840:
77b2f8da +0e ntdll.dll                  NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll             WaitForSingleObjectEx
7668118f +3e kernel32.dll               WaitForSingleObjectEx
76681143 +0d kernel32.dll               WaitForSingleObject
098ab2c9 +21 MADHCNET32.DLL madCodeHook LpcWorkerThread
76683368 +10 kernel32.dll               BaseThreadInitThunk

thread $1b4c:
77b31e27 +0b ntdll.dll     NtTraceControl
77b69fc9 +40 ntdll.dll     EtwpNotificationThread
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $1064:
77b31f4f +0b ntdll.dll     NtWaitForWorkViaWorkerFactory
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $990:
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
76683368 +10 kernel32.dll    BaseThreadInitThunk

CheckWindowConnectionThread ($b58):
77b2f8da +0e ntdll.dll                          NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                     WaitForSingleObjectEx
7668118f +3e kernel32.dll                       WaitForSingleObjectEx
76681143 +0d kernel32.dll                       WaitForSingleObject
098afbb9 +41 MADHCNET32.DLL madNetTools 1277 +6 CheckWindowConnectionThread
76683368 +10 kernel32.dll                       BaseThreadInitThunk

thread $ef8: <priority:15>
77b2f8da +0e ntdll.dll     NtWaitForSingleObject
75780d60 +16 USER32.dll    CallWindowProcW
76683368 +10 kernel32.dll  BaseThreadInitThunk

KeyboardThreadProc ($9f4):
77b30166 +0e ntdll.dll                       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll                  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll                    WaitForMultipleObjectsEx
7578087c +00 USER32.dll                      MsgWaitForMultipleObjectsEx
75780b7c +1a USER32.dll                      MsgWaitForMultipleObjects
4a466fc3 +53 madVR.ax       osd.cpp 2048 +10 COsd.KeyboardThreadMethod
4a46a8ce +5e madVR.ax       osd.cpp 2032  +3 KeyboardThreadProc
76683368 +10 kernel32.dll                    BaseThreadInitThunk

CFrameQueue::RenderThread ($1d8): <priority:2>
77b30166 +00e ntdll.dll                                NtWaitForMultipleObjects
756b1714 +0fa KERNELBASE.dll                           WaitForMultipleObjectsEx
766819f7 +089 kernel32.dll                             WaitForMultipleObjectsEx
766841d3 +013 kernel32.dll                             WaitForMultipleObjects
4a4438f6 +826 madVR.ax       framequeue.cpp 13542 +302 CFrameQueue.RenderThread
4a449cf4 +004 madVR.ax       framequeue.cpp   198   +0 Queue_RenderThread
76683368 +010 kernel32.dll                             BaseThreadInitThunk

CVSync::CollectThreadMethod ($1360): <priority:15>
77b2fd9a +00e ntdll.dll                       NtDelayExecution
4a4d5a11 +071 madVR.ax     tools.cpp 858  +14 SleepMicro
4a4f0c9c +46c madVR.ax     vsync.cpp 820 +172 CVSync.CollectThreadMethod
4a4f28a4 +004 madVR.ax     vsync.cpp  92   +0 VSync_CollectThreadProc
76683368 +010 kernel32.dll                    BaseThreadInitThunk

thread $19ec: <priority:1>
77b2f8da +000e ntdll.dll       NtWaitForSingleObject
756b15c8 +0092 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +003e kernel32.dll    WaitForSingleObjectEx
76681143 +000d kernel32.dll    WaitForSingleObject
77b77290 +0013 ntdll.dll       _vsnprintf
77b8278e +d04b ntdll.dll       RtlVerifyVersionInfo
7669d41c +0011 kernel32.dll    VerifyVersionInfoW
76683368 +0010 kernel32.dll    BaseThreadInitThunk

CVSync::EvaluateThreadMethod ($1194):
77b2f8da +0e ntdll.dll                        NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                   WaitForSingleObjectEx
7668118f +3e kernel32.dll                     WaitForSingleObjectEx
76681143 +0d kernel32.dll                     WaitForSingleObject
4a4f2b09 +79 madVR.ax       vsync.cpp 1359 +5 CVSync.EvaluateThreadMethod
4a4f2d04 +04 madVR.ax       vsync.cpp   98 +0 VSync_EvaluateThreadProc
76683368 +10 kernel32.dll                     BaseThreadInitThunk

thread $39c: <priority:1>
77b2f8da +000e ntdll.dll       NtWaitForSingleObject
756b15c8 +0092 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +003e kernel32.dll    WaitForSingleObjectEx
76681143 +000d kernel32.dll    WaitForSingleObject
77b77290 +0013 ntdll.dll       _vsnprintf
77b8278e +d04b ntdll.dll       RtlVerifyVersionInfo
7669d41c +0011 kernel32.dll    VerifyVersionInfoW
76683368 +0010 kernel32.dll    BaseThreadInitThunk

thread $13a8: <priority:1>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1740: <priority:1>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

CFrameQueue::PresentThread ($17a8): <priority:2>
77b2fd9a +0e ntdll.dll                               NtDelayExecution
756b3d36 +5f KERNELBASE.dll                          SleepEx
756b4607 +0a KERNELBASE.dll                          Sleep
4a442d1b +8b madVR.ax       framequeue.cpp 13052 +14 CFrameQueue.PresentThread
4a4430b4 +04 madVR.ax       framequeue.cpp   199  +0 Queue_PresentThread
76683368 +10 kernel32.dll                            BaseThreadInitThunk

CFrameQueue::IvtcThread ($db8):
77b2f8da +0e ntdll.dll                              NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                         WaitForSingleObjectEx
7668118f +3e kernel32.dll                           WaitForSingleObjectEx
76681143 +0d kernel32.dll                           WaitForSingleObject
4a43e07a +7a madVR.ax       framequeue.cpp 12154 +7 CFrameQueue.IvtcThread
4a4400d4 +04 madVR.ax       framequeue.cpp   194 +0 Queue_IvtcThread
76683368 +10 kernel32.dll                           BaseThreadInitThunk

CFrameQueue::UploadThread ($d68): <priority:1>
77b2f8da +0e ntdll.dll                             NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                        WaitForSingleObjectEx
7668118f +3e kernel32.dll                          WaitForSingleObjectEx
76681143 +0d kernel32.dll                          WaitForSingleObject
4a441faa +7a madVR.ax       framequeue.cpp 9195 +7 CFrameQueue.UploadThread
4a4430a4 +04 madVR.ax       framequeue.cpp  195 +0 Queue_UploadThread
76683368 +10 kernel32.dll                          BaseThreadInitThunk

CFrameQueue::DxvaProcessThread ($19f4):
77b2f8da +0e ntdll.dll                             NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                        WaitForSingleObjectEx
7668118f +3e kernel32.dll                          WaitForSingleObjectEx
76681143 +0d kernel32.dll                          WaitForSingleObject
4a43d96a +7a madVR.ax       framequeue.cpp 9736 +7 CFrameQueue.DxvaProcessThread
4a4400e4 +04 madVR.ax       framequeue.cpp  196 +0 Queue_DxvaProcessThread
76683368 +10 kernel32.dll                          BaseThreadInitThunk

CFrameQueue::SplitThread ($abc):
77b2f8da +0e ntdll.dll                              NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                         WaitForSingleObjectEx
7668118f +3e kernel32.dll                           WaitForSingleObjectEx
76681143 +0d kernel32.dll                           WaitForSingleObject
4a43dcfa +7a madVR.ax       framequeue.cpp 10235 +7 CFrameQueue.SplitThread
4a4400f4 +04 madVR.ax       framequeue.cpp   197 +0 Queue_SplitThread
76683368 +10 kernel32.dll                           BaseThreadInitThunk

CDirect3D::ResetThread ($20c):
77b2f8da +00e ntdll.dll                            NtWaitForSingleObject
756b15c8 +092 KERNELBASE.dll                       WaitForSingleObjectEx
7668118f +03e kernel32.dll                         WaitForSingleObjectEx
76681143 +00d kernel32.dll                         WaitForSingleObject
4a4185bd +13d madVR.ax       direct3d.cpp 5182 +30 CDirect3D.ResetThread
4a418634 +004 madVR.ax       direct3d.cpp 5206  +0 CDirect3D_ResetThread
76683368 +010 kernel32.dll                         BaseThreadInitThunk

thread $1158: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1364: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1650: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $82c: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1004:
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $19b4: <priority:1>
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
766841d3 +13 kernel32.dll    WaitForMultipleObjects
76683368 +10 kernel32.dll    BaseThreadInitThunk

CDirect3D::UpdateHdrPresentationThread ($c7c):
77b2f8da +0e ntdll.dll                            NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll                       WaitForSingleObjectEx
7668118f +3e kernel32.dll                         WaitForSingleObjectEx
76681143 +0d kernel32.dll                         WaitForSingleObject
4a41309b +db madVR.ax       direct3d.cpp 5227 +12 CDirect3D.UpdateHdrPresentationThread
4a415524 +04 madVR.ax       direct3d.cpp 5211  +0 UpdateHdrPresentationThread
76683368 +10 kernel32.dll                         BaseThreadInitThunk

thread $1b18: <priority:15>
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
766841d3 +13 kernel32.dll    WaitForMultipleObjects
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1018: <priority:15>
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
766841d3 +13 kernel32.dll    WaitForMultipleObjects
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1500:
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
7578087c +00 USER32.dll      MsgWaitForMultipleObjectsEx
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $161c: <priority:15>
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
766841d3 +13 kernel32.dll    WaitForMultipleObjects
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1790: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1034: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $10e4: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $1088: <priority:-15>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $14c:
75777908 +26 USER32.dll    GetMessageW
76683368 +10 kernel32.dll  BaseThreadInitThunk

thread $19c8:
77b30166 +00e ntdll.dll                               NtWaitForMultipleObjects
756b1714 +0fa KERNELBASE.dll                          WaitForMultipleObjectsEx
766819f7 +089 kernel32.dll                            WaitForMultipleObjectsEx
7578087c +000 USER32.dll                              MsgWaitForMultipleObjectsEx
75780b7c +01a USER32.dll                              MsgWaitForMultipleObjects
4a42149c +0ac madVR.ax       framequeue.cpp 3559  +20 CFrameQueue.WaitReady
4a4409be +8ae madVR.ax       framequeue.cpp 3849 +255 CFrameQueue.AddFrame
4a46431b +40b madVR.ax       madvr.cpp      5289 +197 CVideoRenderer.Receive
4a40bb0a +04a madVR.ax       customren.cpp  1632   +6 CCustomRendererInputPin.Receive
76683368 +010 kernel32.dll                            BaseThreadInitThunk

thread $1644: <priority:-1>
77b2f8da +0e ntdll.dll       NtWaitForSingleObject
756b15c8 +92 KERNELBASE.dll  WaitForSingleObjectEx
7668118f +3e kernel32.dll    WaitForSingleObjectEx
76681143 +0d kernel32.dll    WaitForSingleObject
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $cb0:
77b2fd9a +0e ntdll.dll       NtDelayExecution
756b3d36 +5f KERNELBASE.dll  SleepEx
756b4607 +0a KERNELBASE.dll  Sleep
76683368 +10 kernel32.dll    BaseThreadInitThunk

thread $f14: <priority:-5>
77b30166 +0e ntdll.dll       NtWaitForMultipleObjects
756b1714 +fa KERNELBASE.dll  WaitForMultipleObjectsEx
766819f7 +89 kernel32.dll    WaitForMultipleObjectsEx
766841d3 +13 kernel32.dll    WaitForMultipleObjects
76683368 +10 kernel32.dll    BaseThreadInitThunk

modules:
00010000 PotPlayerMini.exe                         0, 0, 0, 0         C:\Program Files (x86)\DAUM\PotPlayer
00330000 EasyHk32.dll                              1.23.0.0           C:\Program Files\MacType
03370000 DaumCrashHandler.dll                      1.0.2.4            C:\Program Files (x86)\DAUM\PotPlayer
05220000 ffcodec.dll                                                  C:\Program Files (x86)\DAUM\PotPlayer
09810000 MADHCNET32.DLL                            1.0.18.0           C:\Program_Video\madVR
09a50000 MVRSETTINGS32.DLL                         1.1.15.7           C:\Program_Video\madVR
10000000 MacType.dll                               1.2016.904.0       C:\Program Files\MacType
4a400000 madVR.ax                                  0.92.10.0          C:\Program_Video\madVR
62ce0000 PotPlayer.dll                             1.7.7145.0         C:\Program Files (x86)\DAUM\PotPlayer
64330000 nvwgf2um.dll                              21.21.13.7306      C:\Windows\system32
68290000 nvapi.dll                                 21.21.13.7306      C:\Windows\system32
68610000 d3d11.dll                                 6.2.9200.16570     C:\Windows\system32
687e0000 ntshrui.dll                               6.1.7601.17514     C:\Windows\system32
68b50000 dbghelp.dll                               6.1.7601.17514     C:\Windows\system32
69050000 EhStorShell.dll                           6.1.7600.16385     C:\Windows\system32
690a0000 DUser.dll                                 6.1.7600.16385     C:\Windows\system32
691a0000 srvcli.dll                                6.1.7601.17514     C:\Windows\system32
691c0000 netutils.dll                              6.1.7601.17514     C:\Windows\system32
691d0000 netapi32.dll                              6.1.7601.17887     C:\Windows\system32
69220000 RICHED20.dll                              5.31.23.1230       C:\Windows\system32
696e0000 slc.dll                                   6.1.7600.16385     C:\Windows\system32
696f0000 cscapi.dll                                6.1.7601.17514     C:\Windows\system32
69700000 SbieDll.dll                               5.20.0.0           C:\Program Files\Sandboxie\32
6ad70000 mscms.dll                                 6.1.7601.23677     C:\Windows\system32
6adf0000 DXGIDebug.dll                             9.30.9600.17336    C:\Windows\system32
6ae10000 dxgi.dll                                  6.2.9200.16492     C:\Windows\system32
6ae60000 msmpeg2adec.dll                           6.1.7601.23285     C:\Windows\SysWOW64
6af60000 l3codeca.acm                              1.9.0.401          C:\Windows\SysWOW64
6af80000 DShowRdpFilter.dll                        1.0.0.0            C:\Windows\system32
6aff0000 dxva2.dll                                 6.1.7600.16385     C:\Windows\system32
6b010000 nvd3dum.dll                               21.21.13.7306      C:\Windows\system32
6bdc0000 WindowsCodecs.dll                         6.2.9200.21830     C:\Windows\system32
6c6a0000 assfiltermod.dll                          0.4.0.0            C:\Program_Video\assfiltermod_v0.4_x32
6c7f0000 WMSPDMOD.DLL                              6.1.7601.19091     C:\Windows\SysWOW64
6c8b0000 nvSCPAPI.dll                              7.17.13.7306       C:\Program Files (x86)\NVIDIA Corporation\3D Vision
6c980000 msadp32.acm                               6.1.7600.16385     C:\Windows\system32
6c990000 msgsm32.acm                               6.1.7600.16385     C:\Windows\system32
6c9a0000 msg711.acm                                6.1.7600.16385     C:\Windows\system32
6c9b0000 WMADMOD.DLL                               6.1.7601.19091     C:\Windows\SysWOW64
6ca90000 quartz.dll                                6.6.7601.23709     C:\Windows\SysWOW64
6cc10000 D3D9.DLL                                  6.1.7601.17514     C:\Windows\system32
6ed90000 imaadp32.acm                              6.1.7600.16385     C:\Windows\system32
6eda0000 FaultRep.dll                              6.1.7601.17514     C:\Windows\system32
6ee00000 BROWCLI.DLL                               6.1.7601.17887     C:\Windows\system32
6ee10000 wsock32.dll                               6.1.7600.16385     C:\Windows\system32
6ee20000 d3d8thk.dll                               6.1.7600.16385     C:\Windows\system32
6ee30000 POWRPROF.dll                              6.1.7600.16385     C:\Windows\system32
6ee60000 CONCRT140.dll                             14.10.25008.0      C:\Windows\system32
6eea0000 MSVCP140.dll                              14.10.25008.0      C:\Windows\system32
6ef10000 mfplat.DLL                                12.0.7601.23471    C:\Windows\system32
6ef70000 dsound.dll                                6.1.7600.16385     C:\Windows\system32
6eff0000 midimap.dll                               6.1.7600.16385     C:\Windows\system32
6f000000 MSACM32.dll                               6.1.7600.16385     C:\Windows\system32
6f020000 msacm32.drv                               6.1.7600.16385     C:\Windows\system32
6f030000 AUDIOSES.DLL                              6.1.7601.23471     C:\Windows\system32
6f070000 AVRT.dll                                  6.1.7600.16385     C:\Windows\system32
6f080000 ksuser.dll                                6.1.7601.19091     C:\Windows\system32
6f090000 MMDevAPI.DLL                              6.1.7601.17514     C:\Windows\system32
6f270000 api-ms-win-downlevel-advapi32-l2-1-0.dll  6.2.9200.16492     C:\Windows\system32
6f290000 PROPSYS.dll                               7.0.7601.17514     C:\Windows\system32
6f3d0000 COMCTL32.dll                              6.10.7601.18837    C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d
70110000 wkscli.dll                                6.1.7601.17514     C:\Windows\system32
70120000 wship6.dll                                6.1.7600.16385     C:\Windows\System32
70130000 wdmaud.drv                                6.1.7601.17514     C:\Windows\system32
70160000 DUI70.dll                                 6.1.7600.16385     C:\Windows\system32
70220000 explorerframe.dll                         6.1.7601.23893     C:\Windows\system32
70390000 RICHED32.DLL                              6.1.7601.17514     C:\Windows\system32
703a0000 cryptnet.dll                              6.1.7601.23769     C:\Windows\system32
703c0000 ncrypt.dll                                6.1.7601.23915     C:\Windows\system32
70400000 api-ms-win-crt-environment-l1-1-0.dll     10.0.10586.1171    C:\Windows\system32
70410000 mp3dmod.dll                               6.1.7601.19091     C:\Windows\SysWOW64
70430000 devenum.dll                               6.6.7601.19091     C:\Windows\SysWOW64
70e40000 gdiplus.dll                               6.1.7601.23894     C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.23894_none_5c0be957a009922e
70fe0000 d2d1.dll                                  6.2.9200.16765     C:\Windows\system32
71330000 DWrite.dll                                6.2.9200.22164     C:\Windows\system32
71470000 dwmapi.dll                                6.1.7600.16385     C:\Windows\system32
71600000 WINMM.dll                                 6.1.7601.17514     C:\Windows\system32
71640000 Sensapi.dll                               6.1.7600.16385     C:\Windows\system32
71650000 api-ms-win-downlevel-shlwapi-l2-1-0.dll   6.2.9200.16492     C:\Windows\system32
71660000 perfos.dll                                6.1.7600.16385     C:\Windows\System32
71670000 msdmo.dll                                 6.6.7601.17514     C:\Windows\system32
71690000 MSIMG32.dll                               6.1.7600.16385     C:\Windows\system32
716d0000 bcryptprimitives.dll                      6.1.7601.23451     C:\Windows\SysWOW64
71720000 Secur32.dll                               6.1.7601.23915     C:\Windows\system32
71730000 bcrypt.dll                                6.1.7601.23915     C:\Windows\system32
71900000 RpcRtRemote.dll                           6.1.7601.17514     C:\Windows\system32
72430000 wshtcpip.dll                              6.1.7600.16385     C:\Windows\System32
724d0000 rsaenh.dll                                6.1.7600.16385     C:\Windows\system32
72510000 CRYPTSP.dll                               6.1.7601.23471     C:\Windows\system32
738c0000 WINSTA.dll                                6.1.7601.18540     C:\Windows\system32
73940000 WINNSI.DLL                                6.1.7601.23889     C:\Windows\system32
73950000 IPHLPAPI.DLL                              6.1.7601.17514     C:\Windows\system32
73a80000 DNSAPI.dll                                6.1.7601.17570     C:\Windows\system32
73ad0000 mswsock.dll                               6.1.7601.23451     C:\Windows\system32
742c0000 wtsapi32.dll                              6.1.7601.17514     C:\Windows\system32
742d0000 apphelp.dll                               6.1.7601.17514     C:\Windows\system32
74410000 api-ms-win-crt-locale-l1-1-0.dll          10.0.10586.1171    C:\Windows\system32
74420000 uxtheme.dll                               6.1.7600.16385     C:\Windows\system32
744a0000 api-ms-win-crt-filesystem-l1-1-0.dll      10.0.10586.1171    C:\Windows\system32
744b0000 api-ms-win-crt-time-l1-1-0.dll            10.0.10586.1171    C:\Windows\system32
744c0000 api-ms-win-crt-math-l1-1-0.dll            10.0.10586.1171    C:\Windows\system32
744d0000 api-ms-win-crt-utility-l1-1-0.dll         10.0.10586.1171    C:\Windows\system32
744e0000 api-ms-win-crt-multibyte-l1-1-0.dll       10.0.10586.1171    C:\Windows\system32
744f0000 api-ms-win-crt-convert-l1-1-0.dll         10.0.10586.1171    C:\Windows\system32
74500000 api-ms-win-crt-stdio-l1-1-0.dll           10.0.10586.1171    C:\Windows\system32
74510000 api-ms-win-crt-heap-l1-1-0.dll            10.0.10586.1171    C:\Windows\system32
74520000 api-ms-win-crt-string-l1-1-0.dll          10.0.10586.1171    C:\Windows\system32
74530000 api-ms-win-core-file-l1-2-0.dll           10.0.10586.1171    C:\Windows\system32
74540000 api-ms-win-core-processthreads-l1-1-1.dll 10.0.10586.1171    C:\Windows\system32
74550000 api-ms-win-core-synch-l1-2-0.DLL          10.0.10586.1171    C:\Windows\system32
74560000 api-ms-win-core-localization-l1-2-0.dll   10.0.10586.1171    C:\Windows\system32
74570000 api-ms-win-core-file-l2-1-0.dll           10.0.10586.1171    C:\Windows\system32
74580000 api-ms-win-core-timezone-l1-1-0.dll       10.0.10586.1171    C:\Windows\system32
74590000 ucrtbase.DLL                              10.0.10586.1171    C:\Windows\system32
74680000 api-ms-win-crt-runtime-l1-1-0.dll         10.0.10586.1171    C:\Windows\system32
74690000 VCRUNTIME140.dll                          14.10.25008.0      C:\Windows\system32
75240000 ntmarta.dll                               6.1.7600.16385     C:\Windows\system32
752d0000 version.DLL                               6.1.7600.16385     C:\Windows\system32
753a0000 CRYPTBASE.dll                             6.1.7601.23915     C:\Windows\syswow64
753b0000 SspiCli.dll                               6.1.7601.23915     C:\Windows\syswow64
75410000 iertutil.dll                              11.0.9600.18858    C:\Windows\syswow64
75650000 api-ms-win-downlevel-ole32-l1-1-0.dll     6.2.9200.16492     C:\Windows\syswow64
75660000 normaliz.DLL                              6.1.7600.16385     C:\Windows\syswow64
75670000 WINTRUST.dll                              6.1.7601.23769     C:\Windows\syswow64
756a0000 KERNELBASE.dll                            6.1.7601.23915     C:\Windows\syswow64
75750000 MSASN1.dll                                6.1.7601.17514     C:\Windows\syswow64
75760000 USER32.dll                                6.1.7601.23594     C:\Windows\syswow64
75860000 SHLWAPI.dll                               6.1.7601.17514     C:\Windows\syswow64
758c0000 ole32.dll                                 6.1.7601.23889     C:\Windows\syswow64
75a20000 api-ms-win-downlevel-normaliz-l1-1-0.dll  6.2.9200.16492     C:\Windows\syswow64
75a30000 imagehlp.dll                              6.1.7601.18288     C:\Windows\syswow64
75a60000 NSI.dll                                   6.1.7601.23889     C:\Windows\syswow64
75a70000 DEVOBJ.dll                                6.1.7601.17621     C:\Windows\syswow64
75a90000 LPK.dll                                   6.1.7601.23930     C:\Windows\syswow64
75aa0000 CFGMGR32.dll                              6.1.7601.17621     C:\Windows\syswow64
75ad0000 OLEAUT32.dll                              6.1.7601.23775     C:\Windows\syswow64
75b70000 WLDAP32.dll                               6.1.7601.23889     C:\Windows\syswow64
75bc0000 sechost.dll                               6.1.7600.16385     C:\Windows\SysWOW64
75be0000 WS2_32.dll                                6.1.7601.23451     C:\Windows\syswow64
75c20000 CLBCatQ.DLL                               2001.12.8530.16385 C:\Windows\syswow64
75cb0000 RPCRT4.dll                                6.1.7601.23915     C:\Windows\syswow64
75da0000 USERENV.dll                               6.1.7601.17514     C:\Windows\syswow64
75dc0000 COMDLG32.dll                              6.1.7601.17514     C:\Windows\syswow64
75e40000 SETUPAPI.dll                              6.1.7601.17514     C:\Windows\syswow64
75fe0000 IMM32.DLL                                 6.1.7601.17514     C:\Windows\system32
76040000 PSAPI.DLL                                 6.1.7600.16385     C:\Windows\syswow64
76050000 CRYPT32.dll                               6.1.7601.23769     C:\Windows\syswow64
76180000 MSCTF.dll                                 6.1.7601.23915     C:\Windows\syswow64
76250000 api-ms-win-downlevel-advapi32-l1-1-0.dll  6.2.9200.16492     C:\Windows\syswow64
76260000 urlmon.dll                                11.0.9600.18858    C:\Windows\syswow64
763b0000 WININET.dll                               11.0.9600.18858    C:\Windows\syswow64
76660000 api-ms-win-downlevel-user32-l1-1-0.dll    6.2.9200.16492     C:\Windows\syswow64
76670000 kernel32.dll                              6.1.7601.23915     C:\Windows\syswow64
76780000 GDI32.dll                                 6.1.7601.23914     C:\Windows\syswow64
76810000 shell32.dll                               6.1.7601.23893     C:\Windows\syswow64
77460000 api-ms-win-downlevel-shlwapi-l1-1-0.dll   6.2.9200.16492     C:\Windows\syswow64
77470000 api-ms-win-downlevel-version-l1-1-0.dll   6.2.9200.16492     C:\Windows\syswow64
77480000 msvcrt.dll                                7.0.7601.17744     C:\Windows\syswow64
77530000 ADVAPI32.dll                              6.1.7601.23915     C:\Windows\syswow64
775e0000 USP10.dll                                 1.626.7601.23894   C:\Windows\syswow64
77ae0000 profapi.dll                               6.1.7600.16385     C:\Windows\syswow64
77b10000 ntdll.dll                                 6.1.7601.23915     C:\Windows\SysWOW64

processes:
0000 Idle                           0 0    0
0004 System                         0 0    0
0130 smss.exe                       0 0    0
0200 csrss.exe                      0 0    0
0234 wininit.exe                    0 0    0
023c csrss.exe                      1 0    0
026c services.exe                   0 0    0
0290 winlogon.exe                   1 0    0
02a4 lsass.exe                      0 0    0
02ac lsm.exe                        0 0    0
0310 svchost.exe                    0 0    0
0350 nvvsvc.exe                     0 0    0
0368 nvscpapisvr.exe                0 0    0
0394 svchost.exe                    0 0    0
03fc svchost.exe                    0 0    0
01f8 svchost.exe                    0 0    0
0264 svchost.exe                    0 0    0
02e0 svchost.exe                    0 0    0
053c SbieSvc.exe                    0 0    0
05fc svchost.exe                    0 0    0
0690 spoolsv.exe                    0 0    0
06ac svchost.exe                    0 0    0
0714 svchost.exe                    0 0    0
073c Everything.exe                 0 0    0
0778 IDWinService.exe               0 0    0
07cc IpOverUsbSvc.exe               0 0    0
07d4 InputDirectorSessionHelper.exe 1 0    0
0430 RaRegistry.exe                 0 0    0
0628 RaRegistry64.exe               0 0    0
07fc svchost.exe                    0 0    0
09f8 svchost.exe                    0 0    0
07ac nvxdsync.exe                   1 0    0
04cc taskhost.exe                   1 29   22   normal
0b78 dwm.exe                        1 27   2    high
0ae8 explorer.exe                   1 2632 1588 normal
0be4 taskeng.exe                    1 0    0
0acc MacTray.exe                    1 0    0
050c RAVCpl64.exe                   1 54   19   normal
0b88 VeraCrypt.exe                  1 65   47   normal
0c04 SbieCtrl.exe                   1 232  156  normal
0c10 7+ Taskbar Tweaker.exe         1 24   75   normal
0d4c mt64agnt.exe                   1 0    0
0e2c SearchIndexer.exe              0 0    0
1230 InputDirector.exe              1 0    0
1278 nusb3mon.exe                   1 21   10   normal       C:\Program Files (x86)\Renesas Electronics\USB 3.0 Host Controller Driver\Application
17c8 AlienFusionService.exe         0 0    0
1494 svchost.exe                    0 0    0
13d4 GoogleUpdate.exe               0 0    0
0b80 AlienFusionController.exe      1 27   16   normal       C:\Program Files\Alienware\Command Center
121c Everything.exe                 1 171  68   normal
0b24 SbieSvc.exe                    1 0    0
18f4 audiodg.exe                    0 0    0
1a78 taskhost.exe                   1 0    0
177c chrome.exe                     1 159  75   normal
0ed0 chrome.exe                     1 9    4    normal
1834 chrome.exe                     1 9    4    normal
12e8 chrome.exe                     1 9    5    normal
1658 chrome.exe                     1 4    1    normal
0eac chrome.exe                     1 4    1    normal
1330 chrome.exe                     1 4    1    normal
1bb8 chrome.exe                     1 4    1    normal
07a8 chrome.exe                     1 4    1    normal
0fe0 chrome.exe                     1 4    1    normal
118c chrome.exe                     1 4    1    normal
1300 chrome.exe                     1 4    1    normal
14e0 chrome.exe                     1 4    1    idle
1a9c chrome.exe                     1 4    1    normal
0d9c chrome.exe                     1 4    1    idle
10a4 chrome.exe                     1 4    1    normal
0304 SandboxieRpcSs.exe             1 9    11   normal
0d98 SandboxieDcomLaunch.exe        1 4    6    above normal
13e0 SandboxieCrypto.exe            1 4    3    normal
12c0 dllhost.exe                    1 9    11   normal
0494 PotPlayerMini.exe              1 408  224  above normal C:\Program Files (x86)\DAUM\PotPlayer
1970 dllhost.exe                    1 9    8    normal
04dc madHcCtrl.exe                  1 59   50   normal       C:\Program_Video\madVR
1784 dllhost.exe                    1 9    5    normal

hardware:
+ Computer
  - ACPI x64-based PC
+ Disk drives
  - Hitachi HTS542516K9SA00 ATA Device
  - Hitachi HTS545050B9A300 ATA Device
  - M4-CT128M4SSD2 ATA Device
  - ST31000524AS ATA Device
  - ST31500341AS ATA Device
+ Display adapters
  - NVIDIA GeForce GTX 460 (driver 21.21.13.7306)
  - NVIDIA GeForce GTX 460 (driver 21.21.13.7306)
+ DVD/CD-ROM drives
  - PLDS DVD+-RW DH-24ABS ATA Device
+ Human Interface Devices
  - HID-compliant consumer control device
  - HID-compliant device
  - HID-compliant device
  - HID-compliant device
  - HID-compliant device
  - USB Input Device
  - USB Input Device
  - USB Input Device
  - USB Input Device
+ IDE ATA/ATAPI controllers
  - ATA Channel 0
  - ATA Channel 0
  - ATA Channel 1
  - ATA Channel 1
  - ATA Channel 2
  - ATA Channel 3
  - ATA Channel 4
  - ATA Channel 5
  - Intel(R) 6 Series/C200 Series Chipset Family 6 Port SATA AHCI Controller - 1C02 (driver 9.2.0.1011)
  - Standard Dual Channel PCI IDE Controller
+ Keyboards
  - HID Keyboard Device
  - HID Keyboard Device
+ Mice and other pointing devices
  - HID-compliant mouse
+ Monitors
  - Generic PnP Monitor
+ Network adapters
  - Microsoft 6to4 Adapter
  - Microsoft ISATAP Adapter
  - Microsoft ISATAP Adapter #2
  - Microsoft ISATAP Adapter #3
  - Realtek PCIe GBE Family Controller (driver 7.18.322.2010)
  - Teredo Tunneling Pseudo-Interface
  - WAN Miniport (IKEv2)
  - WAN Miniport (IP)
  - WAN Miniport (IPv6)
  - WAN Miniport (L2TP)
  - WAN Miniport (Network Monitor)
  - WAN Miniport (PPPOE)
  - WAN Miniport (PPTP)
  - WAN Miniport (SSTP)
+ Processors
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
+ Sound, video and game controllers
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - NVIDIA High Definition Audio (driver 1.3.34.15)
  - Realtek High Definition Audio (driver 6.0.1.6240)
+ System devices
  - 2nd generation Intel® Core™ processor family DRAM Controller - 0100 (driver 9.2.0.1011)
  - 2nd generation Intel® Core™ processor family PCI Express Controller - 0101 (driver 9.2.0.1011)
  - 2nd generation Intel® Core™ processor family PCI Express Controller - 0105 (driver 9.2.0.1011)
  - ACPI Fixed Feature Button
  - ACPI Power Button
  - Composite Bus Enumerator
  - Direct memory access controller
  - File as Volume Driver
  - High Definition Audio Controller
  - High Definition Audio Controller
  - High Definition Audio Controller
  - High precision event timer
  - Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 1 - 1C10 (driver 9.2.0.1015)
  - Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 2 - 1C12 (driver 9.2.0.1015)
  - Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 4 - 1C16 (driver 9.2.0.1015)
  - Intel(R) 6 Series/C200 Series Chipset Family SMBus Controller - 1C22 (driver 9.2.0.1011)
  - Intel(R) Management Engine Interface
  - Intel(R) P67 Express Chipset Family LPC Interface Controller - 1C46 (driver 9.2.0.1015)
  - Microsoft ACPI-Compliant System
  - Microsoft System Management BIOS Driver
  - Microsoft Virtual Drive Enumerator Driver
  - Microsoft Windows Management Interface for ACPI
  - Motherboard resources
  - Motherboard resources
  - Motherboard resources
  - Motherboard resources
  - Numeric data processor
  - PCI bus
  - Plug and Play Software Device Enumerator
  - Programmable interrupt controller
  - Remote Desktop Device Redirector Bus
  - System board
  - System board
  - System board
  - System CMOS/real time clock
  - System speaker
  - System timer
  - Terminal Server Keyboard Driver
  - Terminal Server Mouse Driver
  - UMBus Enumerator
  - UMBus Enumerator
  - UMBus Root Bus Enumerator
  - Volume Manager
+ Universal Serial Bus controllers
  - Generic USB Hub
  - Generic USB Hub
  - Generic USB Hub
  - Intel(R) 6 Series/C200 Series Chipset Family USB Enhanced Host Controller - 1C26 (driver 9.2.0.1013)
  - Intel(R) 6 Series/C200 Series Chipset Family USB Enhanced Host Controller - 1C2D (driver 9.2.0.1013)
  - Renesas Electronics USB 3.0 Host Controller (driver 2.0.4.0)
  - Renesas Electronics USB 3.0 Root Hub (driver 2.0.4.0)
  - USB Composite Device
  - USB Root Hub
  - USB Root Hub
+ Xbox Peripherals (legacy)
  - Xbox Controller

cpu registers:
eax = 00000000
ebx = 164a5048
ecx = 163f5b38
edx = 00000000
esi = 163f5b38
edi = 00000000
eip = 6c6c8b28
esp = 1447f804
ebp = 1447f810

stack dump:
1447f804  00 00 00 00 00 00 00 00 - 38 5b 3f 16 44 f8 47 14  ........8[?.D.G.
1447f814  bf 91 6c 6c 00 00 00 00 - 00 00 00 00 00 00 00 00  ..ll............
1447f824  00 00 00 00 00 00 00 00 - bb 5c 5c 74 00 00 6f 00  .........\\t..o.
1447f834  00 00 00 00 00 00 00 00 - 00 00 00 00 e6 8d 6a 6c  ..............jl
1447f844  c4 f8 47 14 f6 8d 6a 6c - 00 00 00 00 00 00 00 00  ..G...jl........
1447f854  6c f8 47 14 e1 ff 60 3d - 00 00 00 00 f8 36 d1 1a  l.G...`=.....6..
1447f864  d8 10 b3 02 02 00 00 00 - 00 00 00 00 00 00 00 00  ................
1447f874  00 00 00 00 d8 7a 6a 19 - c8 10 b3 02 00 00 00 00  .....zj.........
1447f884  00 00 00 00 00 05 00 00 - d0 02 00 00 00 00 00 00  ................
1447f894  00 00 00 00 00 00 00 00 - 00 05 00 00 d0 02 00 00  ................
1447f8a4  d8 10 b3 02 00 00 00 00 - 00 00 00 00 f8 36 d1 1a  .............6..
1447f8b4  e1 ff 60 3d 10 f9 47 14 - 82 7f 75 6c 01 00 00 00  ..`=..G...ul....
1447f8c4  20 f9 47 14 2b 24 44 4a - c8 10 b3 02 00 00 00 00   .G.+$DJ........
1447f8d4  00 00 00 00 62 17 05 00 - 00 00 00 00 02 00 00 00  ....b...........
1447f8e4  86 88 48 3d 00 00 00 00 - f8 36 d1 1a 00 00 00 00  ..H=.....6......
1447f8f4  00 00 00 00 00 00 00 00 - 00 00 00 00 f8 36 d1 1a  .............6..
1447f904  20 52 f9 00 01 00 00 00 - 60 f2 47 14 30 fd 47 14   R......`.G.0.G.
1447f914  30 31 4f 4a 1e 33 54 63 - 00 00 00 00 00 00 00 01  01OJ.3Tc........
1447f924  00 00 00 00 02 00 00 00 - 00 00 00 00 00 00 00 00  ................
1447f934  00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ................

disassembling:
[...]
4a4423f0         mov     edx, [ebp+8]
4a4423f3         push    edx
4a4423f4         mov     ecx, esi
4a4423f6         call    -$ac6b ($4a437790)     ; framequeue.cpp.CFrameQueue.UnlockItem (madVR.ax)
4a4423fb 12279   mov     byte ptr [ebp], 0
4a4423ff 12280   mov     eax, [esi+$555d0]
4a442405         mov     ecx, [eax]
4a442407         mov     edx, [ebp+8]
4a44240a         push    edx
4a44240b         mov     eax, [esi+$556e8]
4a442411         add     eax, ebx
4a442413         mov     edx, [esi+$556ec]
4a442419         adc     edx, edi
4a44241b         push    edx
4a44241c         push    eax
4a44241d         push    edi
4a44241e         push    ebx
4a44241f         mov     eax, [esi+$555d0]
4a442425         push    eax
4a442426         mov     eax, [ecx+$4c]
4a442429       > call    eax
4a44242b         test    eax, eax
4a44242d         jl      loc_4a442471
4a44242f 12282   lea     ecx, [ebp]
4a442432         push    ecx
4a442433         mov     edx, [ebp+$c]
4a442436         push    edx
4a442437         mov     eax, [ebp+8]
4a44243a         push    eax
4a44243b         mov     ecx, esi
4a44243d         call    -$ae12 ($4a437630)     ; framequeue.cpp.CFrameQueue.LockItem (madVR.ax)
4a442442 12283   mov     byte ptr [ebp+$262], 1
4a442449 12284   mov     byte ptr [ebp-$19], 1
4a44244d 12293   mov     dword ptr [ebp-4], $fffffffe
4a442454         call    +$51 ($4a4424aa)
4a442459         jmp     loc_4a442207
4a44245e 12248   add     ecx, 1
4a442461 12249   jmp     loc_4a442268
4a442471 12288   push    0
4a442473         push    0
4a442475         push    0
[...]
```
